#%RAML 1.0
---
title: hackathon API
version: v0.1
protocols: [HTTP]
baseUri: http://localhost:8081/{version}

types:
 searchSchema: !include searchSchema.schema

/index:
  /status:
    get:
      responses:
        200:
          body:
            application/json:
              type: !include statusSchema.schema
              example: !include statusExample.json
  /search:
    get:
      queryParameters:
        text:
          type: string
        size:
          type: number
          default: 12
      responses:
        200:
          body:
            application/json:
              type: searchSchema
              example: !include searchExample.json
  /artifact:
    get:
      queryParameters:
        id:
          type: number
      responses:
        200:
          body:
            application/json:
              ##type: !include artifactSchema.schema
              example: !include artifactExample.json
          
  